### ISSUE TITLE
Multiple files exclusion is not working well

### ISSUE THREAD

**Issue by ramzam062086** [chrisism/VSTS.Robocopy#5]
I have tried to exclude multiple files as well as file extensions (ex: *.pdb,*.exe,sample.dll,test.dll) but its not working fine. Is there any other way to make this work in this plugins?

**Comment by chrisism** [comment]
Follow the guidelines for Robocopy itself. Since this task is only a wrapper it will act exactly the same.
Maybe these links might help with your issue:
https://superuser.com/questions/482112/using-robocopy-and-excluding-multiple-directories
https://social.technet.microsoft.com/Forums/windows/en-US/919ab53c-8a86-439b-bc41-649fce8b9ba1/robocopy-exclude-file-types?forum=w7itprogeneral

**Comment by chrisism** [comment]
Issue gone stale. Closing
